# Python Jupyter Basics

## Python Jupyter Shortcut List:
New code chunks:
- A - New line above selected code chunk
- B - New line below selected code chunk
- X - to cut an entire code chunk
- V - to paste an entire code chunk

Converting to/ from a particular code chunk type:
- M - convert selected code chunk to 'Markdown'
- Y - convert selected code chunk to 'Code'
- R - convert selected code chunk to 'Raw'

## Python Basic Data Types

In [1]:
type("faith")

str

In [2]:
type(0.1)

float

In [3]:
type(1)

int

In [5]:
type(True)

bool

## os Package, to Manage Working Directory

In [249]:
import os
os.getcwd()

'E:\\04-Miscellaneous Work\\14-Python Jupyter'

Note the use of forward slash (/) to define a working directory path name, rather than back slash (\)

In [250]:
os.chdir("E:/04-Miscellaneous Work/14-Python Jupyter")
os.getcwd()

'E:\\04-Miscellaneous Work\\14-Python Jupyter'

Some notes on the use of '.' and '..' in defining a path name:
- '.' denotes the current working folder, whereas
- '..' tells the algorithm to go up one level from the current working folder

# Difference Between List and Arrays
## Lists and Arrays Creation

In [251]:
import numpy as np

In [252]:
range(10)

range(0, 10)

In [253]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [254]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [255]:
np.array(range(5,10))

array([5, 6, 7, 8, 9])

## Lists and Arrays Operations

In [256]:
l = [1,2,3]
a = np.array([1,2,3])

In the case of a **list**, adding a new elemet to a list can be achieved by the .append(), or the '+' sign

In [257]:
l

[1, 2, 3]

In [258]:
l.append(4)
l

[1, 2, 3, 4]

In [259]:
l+[5]

[1, 2, 3, 4, 5]

**The use of '+', *"*"*, or similar notations on an array performs mathematical operations**, as opposed to appending a new element to the array. A sample case for this:

In [260]:
a

array([1, 2, 3])

In [261]:
a+a

array([2, 4, 6])

In [262]:
a*a

array([1, 4, 9])

**NOTE:** Bottomline is, arrays are used for vector operations - the use of the above symbols performs element-wise mathematical operations on the elements of the vectors:
- squaring: a**2
- square root: np.sqrt(a)
- log operation: np.log(a)
- exponent: np.exp(a)

## Vector and Matrix Creation and Operations

Creating a matrix in Python Numpy:
- Method 1: np.array([[1,2] , [3,4]])
- Method 2: np.matrix([[1,2] , [3,4]])

In [263]:
a = np.array([[1,2],[3,4]])
m = np.matrix([[1,2],[3,4]])

The above lines of code creates an array 'a', and a matrix 'm' of the same 2 x 2 (2 by 2) structure.

In [264]:
a

array([[1, 2],
       [3, 4]])

In [265]:
m

matrix([[1, 2],
        [3, 4]])

 **NOTE:** Official Python documentation recommends using the array form instead of matrix whenever possible, for speed of processing. TO convert a matrix into an array, use the **np.array()** function

In [266]:
a_from_m = np.array(m)
type(a_from_m)

numpy.ndarray

In [267]:
type(a)

numpy.ndarray

In [268]:
type(m)

numpy.matrix

## Matrix Characteristics

As the above note suggest, it is more efficient to use array than matrix, as such, this note here is set to serve for documentation purposes only.

### Selecting an Element of a Matrix

It is possible to select a subset of a matrix's element  by specifying its indexes

In [269]:
m

matrix([[1, 2],
        [3, 4]])

In [270]:
m[0,0]

1

In [271]:
m[1,1]

4

**NOTE:** Remember the difference between R and Python indexing system in a [1,2,3,4,5] range

|Element     |  R Index  | Python Index|  Value  |
|------------|-----------|-------------|---------|
|1st element |     1     |      0      |    1    |
|2nd element |     2     |      1      |    2    |
|3rd element |     3     |      2      |    3    |
|4th element |     4     |      3      |    4    |
|5th element |     5     |      4      |    5    |

### Matrix Operations

All of the other matrix operations that are valid for arrays can still be performed for matrices:
- Matrix square: m**2
- Matrix square root: np.sqrt(m)
- Log operations: np.log(m)
- Exponents: np.exp(m)
- Transpose: m.T

# More Matrix Operations

## Matrix Multiplication

Remember the basics of matrix multiplication - the inner dimension of the two matrices being multiplied must be the same, for example:
- matrix A has a dimension of (2,3), and
- matrix B has a dimension of (3,3)

Multiplying matrix AB -> (2,**3) x (3**,3) is **possible**, since the inner dimension of the two matrices match (3 and 3) but

Multiplying matrix BA -> (3,**3) x (2**,3) is **not possible** - since the matrices' inner dimension don't match (3 and 2)

# Basic Packages to Learn
## Numpy, Pandas, Matplotlib Trio
- **Numpy** is the package that contains the functions to perform data science-related tasks (matrix calculation, linear algebra, statistics-related functions etc)
- **Pandas** is the package that contains functions to arrange and tidy up datasets
- **Matplotlib** - Functions to plot and visualize datasets

In [272]:
import numpy as np
import pandas as pd
import matplotlib as mt

## Installing new packages

From the Anaconda Navigator, get to the **Environment** tab on the UI